# Generated by Django 5.1.1 on 2024-09-15 21:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paradero',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('dni', models.CharField(max_length=50, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('id_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elimapass.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('saldo', models.FloatField()),
                ('tipo', models.IntegerField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elimapass.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ParaderoRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paradero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elimapass.paradero')),
                ('id_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elimapass.ruta')),
            ],
            options={
                'unique_together': {('id_ruta', 'id_paradero')},
            },
        ),
    ]
