# Generated by Django 5.1.1 on 2024-09-28 23:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elimapass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='limite',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='Recarga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fecha_hora', models.DateTimeField()),
                ('monto_recargado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medio_pago', models.CharField(max_length=50)),
                ('codigo_tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elimapass.tarjeta')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fecha_hora', models.DateTimeField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elimapass.tarjeta')),
                ('id_bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elimapass.bus')),
            ],
        ),
    ]
