# Generated by Django 5.1.1 on 2024-10-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elimapass', '0002_tarjeta_limite_recarga_viaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='recovery_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
