# Generated by Django 5.1.1 on 2024-10-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elimapass', '0003_usuario_recovery_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
