# Generated by Django 5.1.1 on 2024-10-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elimapass', '0005_remove_viaje_id_bus_remove_viaje_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paraderoruta',
            name='sentido_ida',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='servicio',
            field=models.CharField(default='CORREDOR', max_length=100),
            preserve_default=False,
        ),
    ]
