# Generated by Django 5.1.1 on 2024-11-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elimapass', '0008_alter_bus_latitud_alter_bus_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='paradero',
            name='nombre',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
